{
 "title": "New dashboard",
 "time": { "from": "2024-03-02T00:00:00.000Z", "to": "2024-03-07T00:00:00.000Z" },
 "panels": [
  {
   "title": "drifted columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", drifted_columns_count FROM evidently_report LIMIT 50 "
    }
   ]
  },
  {
   "title": "missing value count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", missing_value_count FROM evidently_report LIMIT 50 "
    }
   ]
  },
  {
   "title": "Value drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", value_drift FROM evidently_report LIMIT 50 "
    }
   ]
  }
 ]
}